# -*- coding: utf-8 -*-
"""simple linear regression.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/127C1WJiYQHuz9s6bw4hqprrXxqCEC21A
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.formula.api as smf

data1 = pd.read_csv("NewspaperData.csv")
data1

data1.info()

data1.describe()

fig,axes=plt.subplots(2,1,figsize=(8,6),gridspec_kw={'height_ratios':[1,3]})
sns.boxplot(data=data1["daily"],ax=axes[0],color='skyblue',width=0.5,orient='h')
axes[0].set_title("Boxplot")
axes[0].set_xlabel("daily")
sns.histplot(data1["daily"],kde=True,ax=axes[1],color='Purple',bins=30)
axes[1].set_title("Histogram with KDE")
axes[1].set_xlabel("Daily")
axes[1].set_ylabel("Y")
plt.tight_layout()
plt.show()

plt.scatter(data1["daily"],
            data1["sunday"])



"""Scatter plot

"""

x=data1["daily"]
y=data1["sunday"]
plt.scatter(data1["daily"], data1["sunday"])
plt.xlim(0, max(x) + 100)
plt.ylim(0, max(y) + 100)
plt.show()

"""Observations
-The relationship between x(daily) and y(sunday) is seen to be linear as seen from scatter plot
-The coreelation is strong and positive with person's corelation coefficient of 0.958154
"""

import statsmodels.formula.api as smf
model1 = smf.ols("sunday~daily", data = data1).fit()

model1.summary()

"""- The predicted equation is y_hat = beta_0 + beta_1 X

- beta0 = 13.8356
- beta1 = 1.3397

- The probability (p-value) for intercept (beta_0) is 0.707 > 0.05

- Therefore the intercept coefficient may not be that much significant in prediction

- However the p-value for "daily" (beta_1) is 0.00 < 0.50

- Therefore the beta_1 coefficient is highly significant and is contribute to prediction
"""

